import { useEffect, useState } from 'react';
import './assertions.css';

type EventType = 'USER_INPUT' | 'MODEL_CALL' | 'TOOL_CALL' | 'AGENT_EVENT';
interface Metrics { success:boolean; verdict:string; tokenUsage:{prompt:number|null;completion:number|null;total:number|null;cached:number|null}; stepCount:number; modelCallCount:number; toolCallCount:number; cacheHitRate:number|null; toolSuccessRate:number|null; toolCalls:{succeeded:number;failed:number;unknown:number}; durationMs:number|null; modelDurationMs:number|null; toolDurationMs:number|null }
interface Artifact { artifactId:string; mediaType:string; sizeBytes:number }
interface AssertionResult { assertionId:string;type:string;verdict:'PASS'|'FAIL'|'ERROR';reason:string;evidence:string[] }
interface SampleDetail { runId:string; sample:{sampleId:string;instruction:string;state:string;summary?:string;assertions?:{results:AssertionResult[];summary:{passed:number;failed:number;errors:number}}}; metrics:Metrics|null; artifacts:Artifact[] }
interface TraceEvent { eventId:string;type:EventType;occurredAt:string;durationMs?:number;round?:number;step?:number;input?:unknown;output?:unknown;request?:unknown;response?:unknown;model?:string;provider?:string;finishReason?:string;usage?:{prompt:number|null;completion:number|null;total:number|null;cached:number|null};toolName?:string;success?:boolean|null;errorCode?:string;name?:string;data?:unknown }
interface TracePage { events:TraceEvent[];pagination:{nextCursor:string|null;totalItems:number} }

async function getJson<T>(url:string):Promise<T>{const response=await fetch(url);const body=await response.json() as T&{error?:{message?:string}};if(!response.ok)throw new Error(body.error?.message??`请求失败：${response.status}`);return body}

export function SampleTraceModal({runId,sampleId,attemptId,onClose}:{runId:string;sampleId:string;attemptId?:string;onClose():void}){
  const[detail,setDetail]=useState<SampleDetail>();const[events,setEvents]=useState<TraceEvent[]>([]);const[nextCursor,setNextCursor]=useState<string|null>(null);const[total,setTotal]=useState(0);const[filter,setFilter]=useState<EventType|''>('');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{void loadInitial()},[runId,sampleId,filter]);
  const basePath=`/api/runs/${runId}/samples/${sampleId}${attemptId?`/attempts/${attemptId}`:''}`;
  async function loadInitial(){setLoading(true);setError('');setEvents([]);setNextCursor(null);try{const detailResult=await getJson<SampleDetail>(basePath);setDetail(detailResult);const trace=await loadTrace(null);setEvents(trace.events);setNextCursor(trace.pagination.nextCursor);setTotal(trace.pagination.totalItems)}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setLoading(false)}}
  async function loadTrace(cursor:string|null){const query=new URLSearchParams({limit:'50'});if(cursor)query.set('cursor',cursor);if(filter)query.set('type',filter);return getJson<TracePage>(`${basePath}/trace?${query}`)}
  async function loadMore(){if(!nextCursor)return;setLoading(true);try{const page=await loadTrace(nextCursor);setEvents(current=>[...current,...page.events]);setNextCursor(page.pagination.nextCursor)}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}finally{setLoading(false)}}
  return <div className="modal-backdrop"><section className="trace-modal" role="dialog" aria-label="样本执行详情"><div className="modal-head"><div><h2>样本执行详情</h2><p>{sampleId} · {attemptId??runId}</p></div><button onClick={onClose}>关闭</button></div>{error&&<div className="error">{error}</div>}{detail&&<><div className="trace-instruction"><b>用户输入</b><p>{detail.sample.instruction}</p>{detail.sample.summary&&<small>最终回复：{detail.sample.summary}</small>}</div><MetricCards metrics={detail.metrics}/><AssertionResults report={detail.sample.assertions}/><div className="artifact-links"><b>原始产物</b>{detail.artifacts.map(item=><a key={item.artifactId} href={`${basePath}/artifacts/${item.artifactId}`} target="_blank" rel="noreferrer">{item.artifactId}<small>{formatBytes(item.sizeBytes)}</small></a>)}</div></>}<div className="trace-toolbar"><div><b>原始轨迹</b><small>{events.length}/{total}</small></div><select aria-label="轨迹类型" value={filter} onChange={event=>setFilter(event.target.value as EventType|'')}><option value="">全部事件</option><option value="MODEL_CALL">模型调用</option><option value="TOOL_CALL">工具调用</option><option value="AGENT_EVENT">Agent事件</option><option value="USER_INPUT">用户输入</option></select></div>{loading&&events.length===0?<p className="trace-loading">加载轨迹中…</p>:<div className="timeline">{events.map(event=><TraceRow key={event.eventId} event={event}/>)}</div>}{nextCursor&&<button className="load-more" disabled={loading} onClick={()=>void loadMore()}>{loading?'加载中…':'加载更多'}</button>}</section></div>;
}

function MetricCards({metrics}:{metrics:Metrics|null}){if(!metrics)return <div className="metrics-empty">该次执行暂无标准化指标</div>;const cards=[['最终结果',metrics.success?'通过':metrics.verdict],['Token',metric(metrics.tokenUsage.total)],['Agent 步数',String(metrics.stepCount)],['缓存命中率',rate(metrics.cacheHitRate)],['工具成功率',rate(metrics.toolSuccessRate)],['总耗时',duration(metrics.durationMs)],['模型调用',String(metrics.modelCallCount)],['工具调用',`${metrics.toolCallCount}（${metrics.toolCalls.failed} 失败）`]];return <div className="metric-grid">{cards.map(([label,value])=><div className="metric-card" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>}
function AssertionResults({report}:{report:SampleDetail['sample']['assertions']}){if(!report)return null;return <section className="assertion-results"><div><b>确定性断言</b><small>{report.summary.passed} 通过 · {report.summary.failed} 未通过 · {report.summary.errors} 异常</small></div>{report.results.map(item=><div className={`assertion-result ${item.verdict}`} key={item.assertionId}><em>{item.verdict}</em><span><strong>{item.type}</strong><small>{item.reason}</small></span></div>)}</section>}
function TraceRow({event}:{event:TraceEvent}){const title=event.type==='MODEL_CALL'?`${event.model??'模型'} · 模型调用`:event.type==='TOOL_CALL'?`${event.toolName??'工具'} · 工具调用`:event.type==='USER_INPUT'?'用户输入':event.name??'Agent 事件';return <details className={`trace-row ${event.type}`}><summary><span className="trace-kind">{kindLabel(event.type)}</span><div><strong>{title}</strong><small>{traceMeta(event)}</small></div>{event.type==='TOOL_CALL'&&<em className={event.success===false?'trace-failed':'trace-ok'}>{event.success==null?'未知':event.success===false?'失败':'成功'}</em>}</summary><div className="trace-body">{event.type==='USER_INPUT'&&<pre>{pretty(event.input)}</pre>}{event.type==='MODEL_CALL'&&<><TraceBlock title="模型输入" value={event.request}/><TraceBlock title="模型输出" value={event.response}/><p className="trace-usage">Prompt {metric(event.usage?.prompt)} · Completion {metric(event.usage?.completion)} · Cached {metric(event.usage?.cached)} · {duration(event.durationMs??null)}</p></>}{event.type==='TOOL_CALL'&&<><TraceBlock title="工具输入" value={event.input}/><TraceBlock title="工具输出" value={event.output}/>{event.errorCode&&<p className="trace-error-code">错误码：{event.errorCode}</p>}</>}{event.type==='AGENT_EVENT'&&<TraceBlock title="事件数据" value={event.data}/>}</div></details>}
function TraceBlock({title,value}:{title:string;value:unknown}){return <details className="trace-block" open><summary>{title}</summary><pre>{value===undefined?'无':pretty(value)}</pre></details>}
function pretty(value:unknown){return typeof value==='string'?value:JSON.stringify(value,null,2)}
function kindLabel(type:EventType){return({USER_INPUT:'USER',MODEL_CALL:'MODEL',TOOL_CALL:'TOOL',AGENT_EVENT:'AGENT'})[type]}
function traceMeta(event:TraceEvent){return[new Date(event.occurredAt).toLocaleTimeString(),event.round!==undefined?`Round ${event.round}`:'',event.step!==undefined?`Step ${event.step}`:'',event.durationMs!==undefined?duration(event.durationMs):''].filter(Boolean).join(' · ')}
function metric(value:number|null|undefined){return value===null||value===undefined?'不可用':value.toLocaleString()}
function rate(value:number|null){return value===null?'不可用':`${(value*100).toFixed(1)}%`}
function duration(value:number|null){return value===null?'不可用':value<1000?`${value}ms`:`${(value/1000).toFixed(2)}s`}
function formatBytes(value:number){return value<1024?`${value} B`:`${(value/1024).toFixed(1)} KB`}
